# Generated by Django 4.2.10 on 2024-02-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_woah", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                fields=("owner", "parent", "kind", "name"),
                name="unique_usergroup_localized_name",
            ),
        ),
    ]
